title: Default Page

columns:

  # main content
  main:
    width: 1/2
    sections:
      content:
        type: fields
        fields:
          broadcast:
            label: Current program
            type:  text
          twitch_channel:
            label: Twitch Channel
            type:  text

          paragraphs:
            label: Paragraphs
            type: structure
            columns:
              title:
                width: 2/8
              text:
                width: 5/8
              inverted:
                width: 1/8
            fields:
              title:
                type: text
              text:
                type: textarea
              inverted:
                type: toggle

          metadesc:
            label: Meta Description
            type: text
            required: true
            validate:
              minLength: 30
              maxLength: 160
            help: Die Meta Description dient der Suchmaschinenoptimierung und sollte zwischen 135 bis 160 Zeichen lang sein. Mehr Infos dazu unter https://yoast.com/meta-descriptions/

  secondary:
    width: 1/2
    sections:
      files:
        sortable: true
        max: 10
        width: 2000
        height: 2000

